Repository alefragnani/vscode-whats-new, pull requests merged in 2021-01, with the labels that each got.

#14 Fix/missing line break on sponsors
  src/PageBuilder.ts
Labels: bug, enhancement

#20 Add support to themeable images on Sponsors (Closes #17)
  src/ContentProvider.ts
  src/PageBuilder.ts
  ui/main.css
Labels: enhancement

#21 Add support to "no issue related" on ChangeLog item (Closes #18)
  src/ContentProvider.ts
  src/PageBuilder.ts
Labels: enhancement

#22 Features/documentation v3
  README.md
  images/whats-new-bookmarks.png
Labels: enhancement

#24 Sync version key
  src/Manager.ts
Labels: enhancement, vscode api adoption
